Bank.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Bank.Domain.Abstract;
using System.Linq;

namespace SportsStore.WebUI.Controllers
{

    public class NavController : Controller
    {
        private readonly ITransctionsRepository _repository;

        public NavController(ITransctionsRepository repo)
        {
            _repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {

            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = _repository.Transactions
                .Select(x => x.Type)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

Bank.WebUI/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bank.Domain.Abstract;
using Bank.Domain.Entities;
using Bank.WebUI.Infrastructure;
using Bank.WebUI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace Bank.WebUI.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ITransctionsRepository _transctions;
        private BankAccountMenager BankManager => HttpContext.GetOwinContext().GetUserManager<BankAccountMenager>();
        public TransactionController(ITransctionsRepository transctions)
        {
            _transctions = transctions;
        }

        private BankAccount GetAccount(string id = "this")
        {
            if (id == "this") id = HttpContext.User.Identity.GetUserId();
            return BankManager.Users.SingleOrDefault(u => u.Id == id);
        }

        public ViewResult History(string category)
        {
            ViewBag.Id = GetAccount().Id;
            var transactions = _transctions.Transactions
                .Where(t => t.Recesiver == ViewBag.Id || t.Sender == ViewBag.Id);
            var viewModel = new HistoryViewModel
            {
                Transactions = transactions
                    .Where(t => category == null || t.Type == category)
                    .OrderBy(t => t.IdTransaction),
                CurrentCategory = category
            };
            return View(viewModel);
        }
    }
}

Bank.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

<h3>Typ:</h3>
<h4>
    @Html.ActionLink("Wszystkie", "History", "Transaction", null,
        new { @class = "" })
</h4>

<h4>
    @Html.RouteLink("Wpłaty", new
    {
        controller = "Transaction",
        action = "History",
        category = "Deposit",
        page = 1
    })
</h4>

<h4>
    @Html.RouteLink("Wypłaty", new
    {
        controller = "Transaction",
        action = "History",
        category = "Withdraw",
        page = 1
    })
</h4>
<h4>
    @Html.RouteLink("Przelewy", new
    {
        controller = "Transaction",
        action = "History",
        category = "Transfer",
        page = 1
    })
</h4>