Bank.WebUI/Models/HistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Bank.Domain.Entities;

namespace Bank.WebUI.Models
{
    public class HistoryViewModel
    {
        public IEnumerable<Transaction> Transactions { get; set; }
        public string CurrentCategory { get; set; }
    }
}

Bank.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Bank.Domain.Abstract;
using System.Linq;

namespace SportsStore.WebUI.Controllers
{

    public class NavController : Controller
    {
        private readonly ITransctionsRepository _repository;

        public NavController(ITransctionsRepository repo)
        {
            _repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {

            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = _repository.Transactions
                .Select(x => x.Type)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

Bank.WebUI/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bank.Domain.Abstract;
using Bank.Domain.Entities;
using Bank.WebUI.Infrastructure;
using Bank.WebUI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace Bank.WebUI.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ITransctionsRepository _transctions;
        private BankAccountMenager BankManager => HttpContext.GetOwinContext().GetUserManager<BankAccountMenager>();
        public TransactionController(ITransctionsRepository transctions)
        {
            _transctions = transctions;
        }

        private BankAccount GetAccount(string id = "this")
        {
            if (id == "this") id = HttpContext.User.Identity.GetUserId();
            return BankManager.Users.SingleOrDefault(u => u.Id == id);
        }

        public ViewResult History(string category)
        {
            ViewBag.Id = GetAccount().Id;
            var transactions = _transctions.Transactions
                .Where(t => t.Recesiver == ViewBag.Id || t.Sender == ViewBag.Id);
            var viewModel = new HistoryViewModel
            {
                Transactions = transactions
                    .Where(t => category == null || t.Type == category)
                    .OrderBy(t => t.IdTransaction),
                CurrentCategory = category
            };
            return View(viewModel);
        }
    }
}

Bank.WebUI/Views/Transaction/History.cshtml
@model Bank.WebUI.Models.HistoryViewModel

@{
    ViewBag.Title = "History";
}

<h2>Historia transakcji</h2>
<div class="row panel">
    <div id="categories" class="col-xs-1">
        @Html.Action("Menu", "Nav")
    </div>
    <div class="col-xs-10">
        <h1></h1>
        <table class="table table-striped">
            <thread>
                <tr>
                    <td>Rodzaj transakcji</td>
                    <td>Konto wejściowe</td>
                    <td>Konto wyjściowe</td>
                    <td>Kwota</td>
                    <td>Data i godzina</td>
                </tr>
            </thread>
            <tbody>
            @foreach (var t in Model.Transactions)
            {
                <tr>
                    <td>
                        @switch (t.Type)
                        {
                            case "Deposit":
                                @:Wpłata na konto
                                break;
                            case "Withdraw":
                                @:Wypłata z konta
                                break;
                            case "Transaction":
                                @:Przelew
                                break;
                            default:
                                @t.Type
                                break;
                        }
                    </td>
                    <td>@t.Recesiver</td>
                    <td>@t.Sender</td>
                    <td>@t.Amount</td>
                    <td>@t.Date.ToString("U")</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>